# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util

import re  # noqa: E501


class AttachmentData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, content=None):  # noqa: E501
        """AttachmentData - a model defined in OpenAPI

        :param name: The name of this AttachmentData.  # noqa: E501
        :type name: str
        :param content: The content of this AttachmentData.  # noqa: E501
        :type content: bytearray
        """
        self.openapi_types = {
            'name': str,
            'content': bytearray
        }

        self.attribute_map = {
            'name': 'name',
            'content': 'content'
        }

        self._name = name
        self._content = content

    @classmethod
    def from_dict(cls, dikt) -> 'AttachmentData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AttachmentData of this AttachmentData.  # noqa: E501
        :rtype: AttachmentData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this AttachmentData.


        :return: The name of this AttachmentData.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AttachmentData.


        :param name: The name of this AttachmentData.
        :type name: str
        """

        self._name = name

    @property
    def content(self):
        """Gets the content of this AttachmentData.


        :return: The content of this AttachmentData.
        :rtype: bytearray
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this AttachmentData.


        :param content: The content of this AttachmentData.
        :type content: bytearray
        """
        if content is not None and not re.search(r'(?<=^data:)(image\/png|image\/jpeg|image\/jpg|application\/pdf)(?=;base64,)', content):  # noqa: E501
            raise ValueError("Invalid value for `content`, must be a follow pattern or equal to `/(?<=^data:)(image\/png|image\/jpeg|image\/jpg|application\/pdf)(?=;base64,)/`")  # noqa: E501

        self._content = content
