# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from api_server.openapi_server import util


class BookingFile(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, date_exported=None, file_name=None):  # noqa: E501
        """BookingFile - a model defined in OpenAPI

        :param date_exported: The date_exported of this BookingFile.  # noqa: E501
        :type date_exported: str
        :param file_name: The file_name of this BookingFile.  # noqa: E501
        :type file_name: str
        """
        self.openapi_types = {
            'date_exported': str,
            'file_name': str
        }

        self.attribute_map = {
            'date_exported': 'date_exported',
            'file_name': 'file_name'
        }

        self._date_exported = date_exported
        self._file_name = file_name

    @classmethod
    def from_dict(cls, dikt) -> 'BookingFile':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BookingFile of this BookingFile.  # noqa: E501
        :rtype: BookingFile
        """
        return util.deserialize_model(dikt, cls)

    @property
    def date_exported(self):
        """Gets the date_exported of this BookingFile.


        :return: The date_exported of this BookingFile.
        :rtype: str
        """
        return self._date_exported

    @date_exported.setter
    def date_exported(self, date_exported):
        """Sets the date_exported of this BookingFile.


        :param date_exported: The date_exported of this BookingFile.
        :type date_exported: str
        """

        self._date_exported = date_exported

    @property
    def file_name(self):
        """Gets the file_name of this BookingFile.


        :return: The file_name of this BookingFile.
        :rtype: str
        """
        return self._file_name

    @file_name.setter
    def file_name(self, file_name):
        """Sets the file_name of this BookingFile.


        :param file_name: The file_name of this BookingFile.
        :type file_name: str
        """

        self._file_name = file_name
