# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class BookingFile(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, export_date=None, booking_file=None, payment_file=None):  # noqa: E501
        """BookingFile - a model defined in OpenAPI

        :param export_date: The export_date of this BookingFile.  # noqa: E501
        :type export_date: str
        :param booking_file: The booking_file of this BookingFile.  # noqa: E501
        :type booking_file: str
        :param payment_file: The payment_file of this BookingFile.  # noqa: E501
        :type payment_file: str
        """
        self.openapi_types = {
            'export_date': str,
            'booking_file': str,
            'payment_file': str
        }

        self.attribute_map = {
            'export_date': 'export_date',
            'booking_file': 'booking_file',
            'payment_file': 'payment_file'
        }

        self._export_date = export_date
        self._booking_file = booking_file
        self._payment_file = payment_file

    @classmethod
    def from_dict(cls, dikt) -> 'BookingFile':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BookingFile of this BookingFile.  # noqa: E501
        :rtype: BookingFile
        """
        return util.deserialize_model(dikt, cls)

    @property
    def export_date(self):
        """Gets the export_date of this BookingFile.


        :return: The export_date of this BookingFile.
        :rtype: str
        """
        return self._export_date

    @export_date.setter
    def export_date(self, export_date):
        """Sets the export_date of this BookingFile.


        :param export_date: The export_date of this BookingFile.
        :type export_date: str
        """

        self._export_date = export_date

    @property
    def booking_file(self):
        """Gets the booking_file of this BookingFile.


        :return: The booking_file of this BookingFile.
        :rtype: str
        """
        return self._booking_file

    @booking_file.setter
    def booking_file(self, booking_file):
        """Sets the booking_file of this BookingFile.


        :param booking_file: The booking_file of this BookingFile.
        :type booking_file: str
        """

        self._booking_file = booking_file

    @property
    def payment_file(self):
        """Gets the payment_file of this BookingFile.


        :return: The payment_file of this BookingFile.
        :rtype: str
        """
        return self._payment_file

    @payment_file.setter
    def payment_file(self, payment_file):
        """Sets the payment_file of this BookingFile.


        :param payment_file: The payment_file of this BookingFile.
        :type payment_file: str
        """

        self._payment_file = payment_file
