# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util

from openapi_server.models.expense_data import ExpenseData  # noqa: E501


class ExpenseDataArray(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, expenses=None):  # noqa: E501
        """ExpenseDataArray - a model defined in OpenAPI

        :param expenses: The expenses of this ExpenseDataArray.  # noqa: E501
        :type expenses: List[ExpenseData]
        """
        self.openapi_types = {
            'expenses': List[ExpenseData]
        }

        self.attribute_map = {
            'expenses': 'expenses'
        }

        self._expenses = expenses

    @classmethod
    def from_dict(cls, dikt) -> 'ExpenseDataArray':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ExpenseDataArray of this ExpenseDataArray.  # noqa: E501
        :rtype: ExpenseDataArray
        """
        return util.deserialize_model(dikt, cls)

    @property
    def expenses(self):
        """Gets the expenses of this ExpenseDataArray.


        :return: The expenses of this ExpenseDataArray.
        :rtype: List[ExpenseData]
        """
        return self._expenses

    @expenses.setter
    def expenses(self, expenses):
        """Sets the expenses of this ExpenseDataArray.


        :param expenses: The expenses of this ExpenseDataArray.
        :type expenses: List[ExpenseData]
        """

        self._expenses = expenses
