# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ExpenseDataFlags(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, declaraties=None):  # noqa: E501
        """ExpenseDataFlags - a model defined in OpenAPI

        :param declaraties: The declaraties of this ExpenseDataFlags.  # noqa: E501
        :type declaraties: List[int]
        """
        self.openapi_types = {
            'declaraties': List[int]
        }

        self.attribute_map = {
            'declaraties': 'declaraties'
        }

        self._declaraties = declaraties

    @classmethod
    def from_dict(cls, dikt) -> 'ExpenseDataFlags':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ExpenseData_flags of this ExpenseDataFlags.  # noqa: E501
        :rtype: ExpenseDataFlags
        """
        return util.deserialize_model(dikt, cls)

    @property
    def declaraties(self):
        """Gets the declaraties of this ExpenseDataFlags.


        :return: The declaraties of this ExpenseDataFlags.
        :rtype: List[int]
        """
        return self._declaraties

    @declaraties.setter
    def declaraties(self, declaraties):
        """Sets the declaraties of this ExpenseDataFlags.


        :param declaraties: The declaraties of this ExpenseDataFlags.
        :type declaraties: List[int]
        """

        self._declaraties = declaraties
