# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ExportFile(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, export_file=None):  # noqa: E501
        """ExportFile - a model defined in OpenAPI

        :param export_file: The export_file of this ExportFile.  # noqa: E501
        :type export_file: str
        """
        self.openapi_types = {
            'export_file': str
        }

        self.attribute_map = {
            'export_file': 'export_file'
        }

        self._export_file = export_file

    @classmethod
    def from_dict(cls, dikt) -> 'ExportFile':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ExportFile of this ExportFile.  # noqa: E501
        :rtype: ExportFile
        """
        return util.deserialize_model(dikt, cls)

    @property
    def export_file(self):
        """Gets the export_file of this ExportFile.


        :return: The export_file of this ExportFile.
        :rtype: str
        """
        return self._export_file

    @export_file.setter
    def export_file(self, export_file):
        """Sets the export_file of this ExportFile.


        :param export_file: The export_file of this ExportFile.
        :type export_file: str
        """

        self._export_file = export_file
