# coding: utf-8

from __future__ import absolute_import

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Status(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, status=None, note=None):  # noqa: E501
        """Status - a model defined in OpenAPI

        :param status: The status of this Status.  # noqa: E501
        :type status: str
        :param note: The note of this Status.  # noqa: E501
        :type note: str
        """
        self.openapi_types = {
            'status': str,
            'note': str,
        }

        self.attribute_map = {
            'status': 'status',
            'note': 'note',
        }

        self._status = status
        self._note = note

    @classmethod
    def from_dict(cls, dikt) -> 'Status':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Status of this Status.  # noqa: E501
        :rtype: Status
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self):
        """Gets the status of this Status.


        :return: The status of this Status.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Status.


        :param status: The status of this Status.
        :type status: str
        """
        if status is None:
            raise ValueError("Invalid value for `amount`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def note(self):
        """Gets the note of this Status.


        :return: The note of this Status.
        :rtype: str
        """
        return self._note

    @note.setter
    def note(self, note):
        """Sets the note of this Status.


        :param note: The note of this Status.
        :type note: str
        """
        self._note = note
