# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.url import Url  # noqa: E501
from openapi_server import util


class UrlArray(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, attachments=None):  # noqa: E501
        """UrlArray - a model defined in OpenAPI

        :param attachments: The attachments of this UrlArray.  # noqa: E501
        :type attachments: List[Url]
        """
        self.openapi_types = {
            'attachments': List[Url]
        }

        self.attribute_map = {
            'attachments': 'attachments'
        }

        self._attachments = attachments

    @classmethod
    def from_dict(cls, dikt) -> 'UrlArray':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UrlArray of this UrlArray.  # noqa: E501
        :rtype: UrlArray
        """
        return util.deserialize_model(dikt, cls)

    @property
    def attachments(self):
        """Gets the attachments of this UrlArray.


        :return: The attachments of this UrlArray.
        :rtype: List[Url]
        """
        return self._attachments

    @attachments.setter
    def attachments(self, attachments):
        """Sets the attachments of this UrlArray.


        :param attachments: The attachments of this UrlArray.
        :type attachments: List[Url]
        """

        self._attachments = attachments
