openapi: 3.0.2
info:
  title: Expenses API
  version: '0.1'
  description: An API for the expenses app
  contact:
    name: VolkerWessels Telecom
    url: 'http://www.volkerwesselstelecom.com'
    email: info@vwt.digital
  license:
    name: GNU GPLv3
    url: 'https://www.gnu.org/licenses/gpl.txt'
  x-audience: company-internal
  x-api-id: 1b66bb9e-5b02-49f1-8cf9-bc3f649d70a6
servers:
  - url: /
paths:
  /employees/expenses:
    post:
      requestBody:
        $ref: '#/components/requestBodies/formData'
      responses:
        '201':
          description: Succesfully made or updated an expense
        default:
          description: Expense Made/Updated successfully!
            security:
                - oauth2: [finance.expenses]
      operationId: add_expense
      summary: Make expense
      description: Create an expense
      x-openapi-router-controller: openapi_server.controllers.expense_controllers
  /employees/cost-types:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CostTypes'
              examples:
                CostTypes:
                  value:
                    CostTypes:
                      - ctype: some text
                        cid: ''
          description: Succesfull response - returns all costtypes
        default:
          description: Cost Types retrieved successfully
            security:
                - oauth2: [finance.expenses]
      operationId: get_cost_types
      summary: Get all cost_types
      description: Retrieve all cost_types
      x-openapi-router-controller: openapi_server.controllers.expense_controllers
  '/employees/expenses/{expenses_id}/documents':
    post:
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Documents'
        required: true
      parameters:
        - $ref: '#/components/parameters/ExpensesId'
      responses:
        '200':
          description: Make new document
        default:
          description: A new document has been made
            security:
                - oauth2: [finance.expenses]
      operationId: add_document
      summary: Make new document
      description: Add a document to an expense
      x-openapi-router-controller: openapi_server.controllers.expense_controllers
  /employees/{employee_id}/expenses:
    get:
      parameters:
        - $ref: '#/components/parameters/EmployeeId'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExpenseDataArray'
              examples:
                ExpenseDataArray:
                  value:
                    Expenses:
                      - amount: ''
                        note: some text
                        cost_type: some text
                        date_of_transaction: 2019-07-16T13:26:00.000Z
                      - amount: ''
                        note: some text
                        cost_type: some text
                        date_of_transaction: 2019-07-16T13:26:00.000Z
          description: Succesfull response - returns all expenses of a logged in employee
        default:
          description: Response Successfully Executed
            security:
                - oauth2: [finance.expenses]
      operationId: get_employee_expenses
      summary: Get all expenses belonging to a specific logged in employee
      description: Retrieve all expenses for a logged in employee
      x-openapi-router-controller: openapi_server.controllers.expense_controllers
  '/employees/expenses/{expenses_id}':
    get:
      parameters:
        - $ref: '#/components/parameters/ExpensesId'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExpenseData'
          description: Successful response - returns information of expense
        default:
          description: Expense Success
            security:
                - oauth2: [finance.expenses]
      operationId: get_expenses
      summary: Get information from expenses by id
      description: Retrieve an expense
      x-openapi-router-controller: openapi_server.controllers.expense_controllers
  '/employees/expenses/{expenses_id}/documents/{documents_id}':
    get:
      parameters:
        - $ref: '#/components/parameters/ExpensesId'
        - $ref: '#/components/parameters/DocumentId'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Documents'
          description: Succesfull response - returns document
        default:
          description: Document successfully Retrieved
            security:
                - oauth2: [finance.expenses]
      operationId: get_document_by_id
      summary: Get document by document id
      x-openapi-router-controller: openapi_server.controllers.expense_controllers
    put:
      parameters:
        - $ref: '#/components/parameters/ExpensesId'
        - $ref: '#/components/parameters/DocumentId'
      responses:
        '200':
          description: Succesfully updated a document
        default:
          description: Expense successfully Updated
            security:
                - oauth2: [finance.expenses]
      operationId: update_attachments_by_id
      summary: Update document by document id
      x-openapi-router-controller: openapi_server.controllers.expense_controllers
    delete:
      parameters:
        - $ref: '#/components/parameters/ExpensesId'
        - $ref: '#/components/parameters/DocumentId'
      responses:
        '200':
          description: Succesfully deleted a document
        default:
          description: Delete Successfull OK
            security:
                - oauth2: [finance.expenses]
      operationId: delete_attachments_by_id
      summary: Delete a document by document id
      x-openapi-router-controller: openapi_server.controllers.expense_controllers
  '/finances/expenses/{document_type}/files':
    get:
      operationId: get_document_list
      summary: Get a list of all booking or payment files
      parameters:
        - $ref: '#/components/parameters/DocumentType'
      responses:
        '200':
          description: Download Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookingFile'
        '401':
          description: The unauthorized client is not allowed to access the authorization grant type.
        '400':
          description: A missing parameter or, unsupported parameter value.
        '403':
          description: The Access token does not have the required scope
        default:
          description: List of files got Successfully OK
            security:
                - oauth2: [creditor.write]
      x-openapi-router-controller: openapi_server.controllers.expense_controllers
    post:
      operationId: create_document
      summary: Creates a single booking or payment document
      parameters:
        - $ref: '#/components/parameters/DocumentType'
        - $ref: '#/components/parameters/DocumentName'
      responses:
        '200':
          description: Download Success
        '401':
          description: The unauthorized client is not allowed to access the authorization grant type.
        '400':
          description: A missing parameter or, unsupported parameter value.
        '403':
          description: The Access token does not have the required scope
        default:
          description: Booking file made Successfully OK
            security:
                - oauth2: [creditor.write]
      x-openapi-router-controller: openapi_server.controllers.expense_controllers
  '/finances/expenses/documents/{document_date}/kinds/{document_type}':
    get:
      operationId: get_document
      summary: Returns a CSV => of a booking file or XML => of payment file
      parameters:
        - $ref: '#/components/parameters/DocumentDate'
        - $ref: '#/components/parameters/DocumentType'

      responses:
        '200':
          description: Download Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookingFile'
        '401':
          description: The unauthorized client is not allowed to access the authorization grant type.
        '400':
          description: A missing parameter or, unsupported parameter value.
        '403':
          description: The Access token does not have the required scope
        default:
          description: Document file successfully retrieved
            security:
                - oauth2: [creditor.write]
      x-openapi-router-controller: openapi_server.controllers.expense_controllers
  '/finances/expenses/{expenses_id}':
    put:
      summary: Update expense
      operationId: update_expenses
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Status'
        required: true
      parameters:
        - $ref: '#/components/parameters/ExpensesId'
      responses:
        '200':
          description: Updated expense
        default:
          description: Status of an expense has been updated
            security:
                - oauth2: [finance.expenses]
      x-openapi-router-controller: openapi_server.controllers.expense_controllers
  /finances/expenses/{expenses_id}/attachments:
    get:
      parameters:
        - $ref: '#/components/parameters/ExpensesId'
      responses:
        '200':
          description: Succesfully received all attachments for expense
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UrlArray'
      summary: Get attachments by expense id
      operationId: get_attachment
        security:
            - oauth2: [finance.expenses]
      x-openapi-router-controller: openapi_server.controllers.expense_controllers
  /finances/expenses:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExpenseDataArray'
              examples:
                ExpenseDataArray:
                  value:
                    Expenses:
                      - amount: ''
                        note: some text
                        cost_type: some text
                        date_of_transaction: 2019-07-16T13:26:00.000Z
                      - amount: ''
                        note: some text
                        cost_type: some text
                        date_of_transaction: 2019-07-16T13:26:00.000Z
          description: Succesfull response - returns all expenses
        default:
          description: Response Successfully Executed
            security:
                - oauth2: [creditor.write]
      operationId: get_all_expenses
      summary: Get all expenses
      description: Retrieve all expenses
      x-openapi-router-controller: openapi_server.controllers.expense_controllers
  /finances/department/{department_id}/expenses:
    get:
      parameters:
        - $ref: '#/components/parameters/DepartmentId'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExpenseDataArray'
              examples:
                ExpenseDataArray:
                  value:
                    Expenses:
                      - amount: ''
                        note: some text
                        cost_type: some text
                        date_of_transaction: 2019-07-16T13:26:00.000Z
                      - amount: ''
                        note: some text
                        cost_type: some text
                        date_of_transaction: 2019-07-16T13:26:00.000Z
          description: Succesfull response - returns all expenses
        default:
          description: Response Successfully Executed
            security:
                - oauth2: [manager.write]
      operationId: get_department_expenses
      summary: Get all expenses belonging to a specific manager
      description: Retrieve all expenses for a given manager
      x-openapi-router-controller: openapi_server.controllers.expense_controllers

components:
  schemas:
    Url:
      properties:
        url:
          type: string
      example:
        url: 'https://gcp.com/img.png'
    UrlArray:
      title: Root Type for UrlArray
      description: Array of urls of attachments
      type: object
      properties:
        attachments:
          type: array
          items:
            $ref: '#/components/schemas/Url'
    Status:
      description: Status for expense
      properties:
        status:
          type: string
        creditor_note:
          type: string
        manager_note:
          type: string
      required:
        - status
      example:
        status: 'cancelled_by_creditor'
        finance_note: 'Wrong amount'
    Documents:
      description: Information for documents
      properties:
        document:
          format: binary
          type: string
      example:
        document: ''
    ExpenseData:
      title: expenseData
      description: Form data to an expense
      required:
        - amount
        - note
        - cost_type
        - date_of_transaction
        - attachment
      type: object
      properties:
        amount:
          format: decimal
          type: number
        note:
          type: string
        cost_type:
          type: string
        date_of_transaction:
          type: integer
        attachment:
          type: string
      example: |-
        {
            "note": "This is a note",
            "id": "R1rt2345",
            "amount": 45.56,
            "cost_type": "Office Utilities",
            "date_of_transaction": "2019-07-16T13:26:00.000Z"
            "status": "new"
        }
    ExpenseDataArray:
      title: Root Type for ExpenseDataArray
      description: Array of expense data
      type: object
      properties:
        expenses:
          type: array
          items:
            $ref: '#/components/schemas/ExpenseData'
      example:
        Expenses:
          - note: |
              This is a note
            id: |
              R1rt2345
            amount: 45.56
            cost_type: |
              This is a cost_type
            status: new
            date_of_transaction: 2019-07-16T13:26:00.000Z"
          - note: |
              This is a notes
            id: |
              R1rt23f45
            amount: 45.16
            cost_type: |
              This is a cost_type
            status: opened
            date_of_transaction: 2014-01-16T10:04:00.000X"
    CostTypes:
      title: costTypes
      description: CostType data
      required:
        - cid
        - ctype
      type: object
      properties:
        cid:
          type: string
          description: A cost type doel organisation code
        ctype:
          type: string
      example: |-
        {
            "cid": "410200",
            "ctype": "Omschrijving"
        }
    BookingFile:
      title: Exported files
      description: Booking File Exported data
      type: object
      properties:
        date_exported:
          type: string
        file_name:
          type: string
      example: |-
        {
            "date_exported": "13:39:00-19072019"
            "file_name": "13:39:00-19072019"
        }
  parameters:
    DocumentDate:
      name: document_date
      schema:
        type: string
      in: path
      required: true
    ExpensesId:
      style: simple
      explode: false
      name: expenses_id
      schema:
        type: integer
      in: path
      required: true
    EmployeeId:
      style: simple
      explode: false
      name: employee_id
      schema:
        type: string
      in: path
      required: true
    DepartmentId:
      style: simple
      explode: false
      name: department_id
      schema:
        type: string
      in: path
      required: true
    DocumentId:
      style: simple
      explode: false
      name: documents_id
      schema:
        type: integer
      in: path
      required: true
    DocumentName:
      style: simple
      explode: false
      name: name
      schema:
        type: string
      in: query
      required: false
    DocumentType:
      style: simple
      explode: false
      name: document_type
      schema:
        type: string
      in: path
      required: false
  requestBodies:
    formData:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ExpenseData'
      required: true
  securitySchemes:
    oauth2:
      type: oauth2
      description: This API uses OAuth 2 with the implicit grant flow.
      flows:
        clientCredentials:
          authorizationUrl: >-
            https://azuread.url/2.0/authorize
          tokenUrl: >-
            https://azuread.url/v2.0/token
          scopes:
            manager.write: Read all expenses and documents
            creditor.write: Write all expenses and documents
            finance.expenses: Read expense and document information
      x-tokenInfoFunc: openapi_server.controllers.security_controller_.info_from_oAuth2
      x-scopeValidateFunc: connexion.decorators.security.validate_scope
