# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Documents(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, document=None):  # noqa: E501
        """Documents - a model defined in OpenAPI

        :param document: The document of this Documents.  # noqa: E501
        :type document: file
        """
        self.openapi_types = {
            'document': file
        }

        self.attribute_map = {
            'document': 'document'
        }

        self._document = document

    @classmethod
    def from_dict(cls, dikt) -> 'Documents':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Documents of this Documents.  # noqa: E501
        :rtype: Documents
        """
        return util.deserialize_model(dikt, cls)

    @property
    def document(self):
        """Gets the document of this Documents.


        :return: The document of this Documents.
        :rtype: file
        """
        return self._document

    @document.setter
    def document(self, document):
        """Sets the document of this Documents.


        :param document: The document of this Documents.
        :type document: file
        """

        self._document = document
