# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Image(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, image=None):  # noqa: E501
        """Image - a model defined in OpenAPI

        :param image: The image of this Image.  # noqa: E501
        :type image: file
        """
        self.openapi_types = {
            'image': file
        }

        self.attribute_map = {
            'image': 'image'
        }

        self._image = image

    @classmethod
    def from_dict(cls, dikt) -> 'Image':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The image of this Image.  # noqa: E501
        :rtype: Image
        """
        return util.deserialize_model(dikt, cls)

    @property
    def image(self):
        """Gets the image of this Image.


        :return: The image of this Image.
        :rtype: file
        """
        return self._image

    @image.setter
    def image(self, image):
        """Sets the image of this Image.


        :param image: The image of this Image.
        :type image: file
        """
        if image is None:
            raise ValueError("Invalid value for `image`, must not be `None`")  # noqa: E501

        self._image = image
